### ISSUE TITLE
Removing `mesh` field from Mesh object

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#178]
```yaml
type: Mesh
name: default
mesh: default
mtls:
  enabled: true
  ca:
    builtin: {}
```

becomes:

```yaml
type: Mesh
name: default
mtls:
  enabled: true
  ca:
    builtin: {}
```
