### ISSUE TITLE
MacOS install failed(v0.12)

### ISSUE THREAD

**Issue by smwyzi** [Kong/kuma#291]
https://kuma.io/docs/0.1.2/installation/macos/
hi, when I follow this website to install kuma on macos, it failed when i run
```
KUMA_CONTROL_PLANE_BOOTSTRAP_SERVER_URL=http://127.0.0.1:5682 \
  KUMA_DATAPLANE_MESH=default \
  KUMA_DATAPLANE_NAME=dp-echo-1 \
  kuma-dp run
```
the log said:
```
[2019-09-25 13:22:18.388][909834][critical][main] external/envoy/source/server/server.cc:78] error initializing configuration '/tmp/kuma.io/envoy/bootstrap.yaml': Proto constraint validation failed (BootstrapValidationError.Admin: ["value is required"]):
```

hope to get help, thanks==

**Comment by devadvocado** [comment]
hey @smwyzi, would you kindly show me the output of the bootstramp.yaml in /tmp/kuma.io/envoy/bootstrap.yaml

**Comment by smwyzi** [comment]
yes
```
cat /tmp/kuma.io/envoy/bootstrap.yaml
dynamicResources:
  adsConfig:
    apiType: GRPC
    grpcServices:
    - envoyGrpc:
        clusterName: ads_cluster
  cdsConfig:
    ads: {}
  ldsConfig:
    ads: {}
node:
  cluster: echo
  id: default.dp-echo-1.default
staticResources:
  clusters:
  - connectTimeout: 0.250s
    http2ProtocolOptions: {}
    loadAssignment:
      clusterName: ads_cluster
      endpoints:
      - lbEndpoints:
        - endpoint:
            address:
              socketAddress:
                address: 127.0.0.1
                portValue: 5678
    name: ads_cluster
    type: STRICT_DNS
    upstreamConnectionOptions:
      tcpKeepalive: {}
```
