### ISSUE TITLE
Dataplane config not found through bootstrap or kumactl but available through REST API

### ISSUE THREAD

**Issue by rucciva** [Kong/kuma#387]
### Summary

kumactl get dataplanes result in 0 dataplanes and starting a configured dataplane result in 404 error. Meanwhile obtaining dataplanes config through REST API return stored configuration.

### Steps To Reproduce

1. start kuma cp in universal mode with postgres database
2. enable mtls
3. add allow all Traffic Permission through kumactl
4. add a dataplane through kumactl
5. confirm dataplane config existence through rest api `/meshes/{name}/dataplanes/{name}`
6. kumactl get dataplanes, **result in zero dataplanes**
7. start dataplane, **result in bootstrap error due to 404 error**

### Additional Details & Logs

- Version: **0.2.2**
- Error logs: 

```
ERROR   kuma-dp.run     problem running Dataplane (Envoy)       {"error": "failed to generate Envoy bootstrap config: status: 404. Did you first applied Dataplane resource?", "errorVerbose": "status: 404. Did you first applied Dataplane resource?\ngithub.com/Kong/kuma/app/kuma-dp/pkg/dataplane/envoy.(*remoteBootstrap).Generate\n\t/go/src/github.com/Kong/kuma/app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go:46\ngithub.com/Kong/kuma/app/kuma-dp/pkg/dataplane/envoy.(*Envoy).Run\n\t/go/src/github.com/Kong/kuma/app/kuma-dp/pkg/dataplane/envoy/envoy.go:90\ngithub.com/Kong/kuma/app/kuma-dp/cmd.newRunCmd.func1.3\n\t/go/src/github.com/Kong/kuma/app/kuma-dp/cmd/run.go:84\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337\nfailed to generate Envoy bootstrap config\ngithub.com/Kong/kuma/app/kuma-dp/pkg/dataplane/envoy.(*Envoy).Run\n\t/go/src/github.com/Kong/kuma/app/kuma-dp/pkg/dataplane/envoy/envoy.go:92\ngithub.com/Kong/kuma/app/kuma-dp/cmd.newRunCmd.func1.3\n\t/go/src/github.com/Kong/kuma/app/kuma-dp/cmd/run.go:84\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}
```

- Configuration

    - Kuma CP:
    ```
    version: "2.2"
    services:
      postgres:
        image: postgres:10.1-alpine
        restart: unless-stopped
        environment:
          POSTGRES_DB: kuma
          POSTGRES_USER: kuma
          POSTGRES_PASSWORD: kuma
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5
      
      kuma_database:
        image: postgres:10.1-alpine
        restart: on-failure
        depends_on:
          postgres:
            condition: service_healthy 
        environment:
          SQL: |-
            CREATE TABLE IF NOT EXISTS resources (
              name        varchar(100) NOT NULL,
              namespace   varchar(100) NOT NULL,
              mesh        varchar(100) NOT NULL,
              type        varchar(100) NOT NULL,
              version     integer NOT NULL,
              spec        text,
              PRIMARY KEY (name, namespace, mesh, type)
            );
        entrypoint: /bin/sh -c
        command: 
          - echo "$$SQL" | PGPASSWORD=kuma psql -h postgres -U kuma -d kuma
    
      kuma_cp:
        image: kong-docker-kuma-docker.bintray.io/kuma-cp:0.2.2
        restart: unless-stopped
        depends_on:
          postgres:
            condition: service_healthy 
          kuma_database:
            condition: service_started
        environment:
          KUMA_STORE_TYPE: postgres
          KUMA_STORE_POSTGRES_HOST: postgres
          KUMA_STORE_POSTGRES_PORT: 5432
          KUMA_STORE_POSTGRES_USER: kuma
          KUMA_STORE_POSTGRES_PASSWORD: kuma
          KUMA_STORE_POSTGRES_DB_NAME: kuma
        ports:
          - 5677:5677
          - 5678:5678
          - 5680:5680
          - 5681:5681
          - 5682:5682
        command: --log-level debug run
    ```

    - Mesh
    
    ```
    type: Mesh
    name: some.mesh
    mtls:
    enabled: true
    ca:
        builtin: {}
    ```

    - Traffic Permission
    ```
    type: TrafficPermission
    name: permission
    mesh: some.mesh
    rules:
    - sources:
        - match:
            service: "*"
        destinations:
        - match:
            service: "*"
            version: "*"
    ```

    - Dataplane:
    ```
    type: Dataplane
    mesh: some.mesh
    name: crontab_ui-1
    networking:
      inbound:
      - interface: 0.0.0.0:63080:8000
        tags:
          service: crontab_ui
    ```

    - Kuma DP:
    ```
    kuma_dp:
      image: kong-docker-kuma-docker.bintray.io/kuma-dp:0.2.2
      restart: unless-stopped
      environment:
        KUMA_CONTROL_PLANE_BOOTSTRAP_SERVER_URL: http://some.ip:5682
        KUMA_DATAPLANE_MESH: some.mesh
        KUMA_DATAPLANE_NAME: crontab_ui-1
      network_mode: "service:crontab_ui"
      command: --log-level debug run
    ```

    - Dataplanes config through rest api
    ```
    curl some.ip:5681/meshes/some.mesh/dataplanes/crontab_ui-1

    response: 
    {
        "mesh": "some.mesh",
        "name": "crontab_ui-1",
        "networking": {
            "inbound": [
                {
                    "interface": "0.0.0.0:63080:8000",
                    "tags": {
                        "service": "crontab_ui"
                    }
                }
            ]
        },
        "type": "Dataplane"
    }

    ```

    

- Platform and Operating System: **Ubuntu with Docker**
