### ISSUE TITLE
How to use ProxyTemplate to create frontendpoint

### ISSUE THREAD

**Issue by dgoujard** [Kong/kuma#406]
Hello,

I use Kuma on baremetal servers and docker.
I would like to create and endpoint for grpc-web clients.
I thinking using ProxyTemplate to create an ingress endpoint.
Here my yaml :
```
type: ProxyTemplate
mesh: default
name: template-1
selectors:
  - match:
      service: auth
conf:
  imports:
    - default-proxy
  resources:
    - name: inbound:0.0.0.0:4040
      version: v1
      resource: |
        '@type': type.googleapis.com/envoy.api.v2.Listener
        name: inbound:0.0.0.0:4040
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 4040
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              name: ingressroute
              codec_type: auto
              route_config:
                virtual_hosts:
                - routes:
                  - match:
                      prefix: "/auth"
                    route:
                      cluster: localhost:PORTAUTHDATAPLACESERVICE
                  domains:
                  - "*"
                  name:  echo_service
              http_filters:
                name: envoy.grpc_web
                name: envoy.router
              stat_prefix: ingress_http
```
I excepted, on each auth service "instance", to had one additional listener on port 4040.
With this ingress "controller" i would like to open some service to web clients with path style attributes.

The Dataplane with auth service seam to understand the change, i has this logs : 
```
[2019-11-03 18:21:05.861][1194788][info][upstream] [external/envoy/source/server/lds_api.cc:42] lds: remove listener 'outbound:127.0.0.1:10002'
[2019-11-03 18:21:05.861][1194788][info][upstream] [external/envoy/source/server/lds_api.cc:42] lds: remove listener 'inbound:127.0.0.1:8010'
[2019-11-03 18:21:05.861][1194788][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:548] removing cluster localhost:80
[2019-11-03 18:21:05.861][1194788][info][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:548] removing cluster auth
```

> ➜  ~ curl http://localhost:4040
> curl: (7) Failed to connect to localhost port 4040: Connection refused

The configdump from envoy:
```
{
 "configs": [
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.BootstrapConfigDump",
   "bootstrap": {
    "node": {
     "id": "default.backend-1.default",
     "cluster": "backend",
     "build_version": "7a12f379e47a9f7cf7211c727fe8fc70b6a0a9ab/1.11.2/clean-getenvoy-b8451b1-envoy/RELEASE/BoringSSL"
    },
    "static_resources": {
     "clusters": [
      {
       "name": "ads_cluster",
       "type": "STRICT_DNS",
       "connect_timeout": "1s",
       "http2_protocol_options": {},
       "upstream_connection_options": {
        "tcp_keepalive": {}
       },
       "load_assignment": {
        "cluster_name": "ads_cluster",
        "endpoints": [
         {
          "lb_endpoints": [
           {
            "endpoint": {
             "address": {
              "socket_address": {
               "address": "127.0.0.1",
               "port_value": 5678
              }
             }
            }
           }
          ]
         }
        ]
       }
      },
      {
       "name": "access_log_sink",
       "type": "STATIC",
       "connect_timeout": "1s",
       "http2_protocol_options": {},
       "upstream_connection_options": {
        "tcp_keepalive": {}
       },
       "load_assignment": {
        "cluster_name": "access_log_sink",
        "endpoints": [
         {
          "lb_endpoints": [
           {
            "endpoint": {
             "address": {
              "pipe": {
               "path": "/tmp/kuma-access-logs-backend-1-default.sock"
              }
             }
            }
           }
          ]
         }
        ]
       }
      }
     ]
    },
    "dynamic_resources": {
     "lds_config": {
      "ads": {}
     },
     "cds_config": {
      "ads": {}
     },
     "ads_config": {
      "api_type": "GRPC",
      "grpc_services": [
       {
        "envoy_grpc": {
         "cluster_name": "ads_cluster"
        }
       }
      ]
     }
    },
    "admin": {
     "access_log_path": "/dev/null",
     "address": {
      "socket_address": {
       "address": "127.0.0.1",
       "port_value": 9901
      }
     }
    }
   },
   "last_updated": "2019-11-03T17:19:52.850Z"
  },
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.ClustersConfigDump",
   "version_info": "517687ea-fe5e-11e9-84c5-3c15c2e86aae",
   "static_clusters": [
    {
     "cluster": {
      "name": "access_log_sink",
      "type": "STATIC",
      "connect_timeout": "1s",
      "http2_protocol_options": {},
      "upstream_connection_options": {
       "tcp_keepalive": {}
      },
      "load_assignment": {
       "cluster_name": "access_log_sink",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "pipe": {
              "path": "/tmp/kuma-access-logs-backend-1-default.sock"
             }
            }
           }
          }
         ]
        }
       ]
      }
     },
     "last_updated": "2019-11-03T17:19:52.854Z"
    },
    {
     "cluster": {
      "name": "ads_cluster",
      "type": "STRICT_DNS",
      "connect_timeout": "1s",
      "http2_protocol_options": {},
      "upstream_connection_options": {
       "tcp_keepalive": {}
      },
      "load_assignment": {
       "cluster_name": "ads_cluster",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "127.0.0.1",
              "port_value": 5678
             }
            }
           }
          }
         ]
        }
       ]
      }
     },
     "last_updated": "2019-11-03T17:19:52.854Z"
    }
   ]
  },
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.ListenersConfigDump",
   "version_info": "517687cc-fe5e-11e9-84c5-3c15c2e86aae"
  }
 ]
}

```

Maybe i misunderstand something, grpc and mesh are new for me.

Thank you

**Comment by yskopets** [comment]
@dgoujard Hi!

Thanks a lot for your interest in Kuma! 👍 

Let me take a look into this.

**Comment by dgoujard** [comment]
@yskopets 
Thank you for your fast reply, Kuma seams to be the only mesh service easy to use on baremetal servers. 
Other alternative is envoy but it's a lot of config files.
Kuma sound like to Kubernetes style configuration/spirit

**Comment by yskopets** [comment]
@dgoujard Hey!

Integration with `Kong` is not ready yet, but it's one of our priorities.

Back to your original question.

There are a couple issues in the attached configuration. Let me explain how to fix that.

1. The format of `ProxyTemplate` is slightly different than documented at https://kuma.io (sorry, our bad 😞):

Instead of 

```yaml
type: ProxyTemplate
mesh: default
name: template-1
selectors:
  ...
conf:
  imports:
  ...
  resources:
  ...
```

it's

```yaml
type: ProxyTemplate
mesh: default
name: template-1
selectors:
  ...
imports:
  ...
resources:
  ...
```

Notices that `selectors`, `imports` and `resources` fields are at the same level.

2. Inside a `type.googleapis.com/envoy.api.v2.Listener`

Instead of

```yaml
  ...
  http_filters:
    name: envoy.grpc_web
    name: envoy.router
```

it should be

```yaml
  ...
  http_filters:
  - name: envoy.grpc_web
  - name: envoy.router
```

Notice that `http_filters` is a list rather than map.

3. Inside a `type.googleapis.com/envoy.api.v2.Listener`

The following configuration is incomplete

```yaml
  ...
  route:
    cluster: localhost:PORTAUTHDATAPLACESERVICE
```

If you're trying to refer to an existing `Cluster` auto-generated by `Kuma`, it will not work.

The `Cluster` generated by `Kuma` has configuration suitable for L4 proxying, while you need a `Cluster` with configuration for L7 (HTTP2/gRPC).

You need to add a custom `Cluster` to the list of `resources`, e.g.

```yaml
type: ProxyTemplate
mesh: default
name: grpc-web
selectors:
- match:
    service: grpc-service
imports:
  - default-proxy
resources:
  - name: inbound:0.0.0.0:4040
    version: v1
    resource: |
      '@type': type.googleapis.com/envoy.api.v2.Listener
      ...
  - name: custom:127.0.0.1:9090
    version: v1
    resource: |
      '@type': type.googleapis.com/envoy.api.v2.Cluster
      name: custom:127.0.0.1:9090
      connectTimeout: 5s
      http2_protocol_options: {}
      loadAssignment:
        clusterName: custom:127.0.0.1:9090
        endpoints:
        - lbEndpoints:
          - endpoint:
              address:
                socketAddress:
                  address: 127.0.0.1
                  portValue: 9090
      type: STATIC  
```

Notice an extra `Cluster` named `custom:127.0.0.1:9090`.

It has `http2_protocol_options: {}` which is required for HTTP2/gRPC proxying.

---

So, here is a complete example.

Let's go through [gRPC-Web Hello World Guide](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld) and use `Kuma` instead of vanilla `Envoy`.

1. Let's create a `Dataplane` for gRPC server

```bash
echo "type: Dataplane
mesh: default
name: grpc-server
networking:
  inbound:
  - interface: 0.0.0.0:19090:9090
    tags:
      service: grpc-service" | kumactl apply -f -
```

Notice that the original gRPC server will be listening on `0.0.0.0:9090`.

Based on the above `Dataplane` resource, `Kuma` will configure `Envoy` to listen on `0.0.0.0:19090`.

This `Listener` is meant for `service-to-service` traffic inside the mesh.

However, it's not suitable for ingress traffic.

2. Let's define a `ProxyTemplate` to create a `Listener` with gRPC-Web settings:

```bash
echo "type: ProxyTemplate
mesh: default
name: grpc-web
selectors:
- match:
    service: grpc-service
imports:
  - default-proxy
resources:
  - name: custom:inbound:0.0.0.0:8080
    version: v1
    resource: |
      '@type': type.googleapis.com/envoy.api.v2.Listener
      name: custom:inbound:0.0.0.0:8080
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
      - filters:
        - name: envoy.http_connection_manager
          config:
            name: ingressroute
            codec_type: auto
            route_config:
              virtual_hosts:
              - routes:
                - match:
                    prefix: '/'
                  route:
                    cluster: custom:127.0.0.1:9090
                cors:
                  allow_origin:
                  - '*'
                  allow_methods: GET, PUT, DELETE, POST, OPTIONS
                  allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                  max_age: '1728000'
                  expose_headers: custom-header-1,grpc-status,grpc-message
                domains:
                - '*'
                name:  echo_service
            http_filters:
            - name: envoy.grpc_web
            - name: envoy.cors
            - name: envoy.router
            stat_prefix: ingress_http
  - name: custom:127.0.0.1:9090
    version: v1
    resource: |
      '@type': type.googleapis.com/envoy.api.v2.Cluster
      name: custom:127.0.0.1:9090
      connectTimeout: 5s
      http2_protocol_options: {}
      loadAssignment:
        clusterName: custom:127.0.0.1:9090
        endpoints:
        - lbEndpoints:
          - endpoint:
              address:
                socketAddress:
                  address: 127.0.0.1
                  portValue: 9090
      type: STATIC" | kumactl apply -f -
```

Based on the above `ProxyTemplate` resource, `Kuma` will configure `Envoy` to listen on `0.0.0.0:8080`.

3. Now, you can complete the rest of  [gRPC-Web Hello World Guide](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld):

- start gRPC server

```bash
node server.js
```

- start web server

```bash
python3 -m http.server 8081
```
- navigate to `http://localhost:8081` and check out the contents of developer console

---

Hope that helps!

Let me know if you still have some questions.
