### ISSUE TITLE
ProxyTemplate has a different format than documented on kuma.io

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#407]
### Summary

* apparently, `ProxyTemplate` resource has a slightly different format than documented on https://kuma.io
* `universal`: 

  on `kuma.io`:

  ```yaml
  type: ProxyTemplate
  mesh: default
  name: template-1
  selectors:
    ...
  conf:
    imports:
    ...
    resources:
    ...
  ```

  actually implemented:

  ```yaml
  type: ProxyTemplate
  mesh: default
  name: template-1
  selectors:
    ...
  imports:
    ...
  resources:
    ...
  ```

* `kubernetes`:

  on `kuma.io`:

  ```yaml
  apiVersion: kuma.io/v1alpha1
  kind: ProxyTemplate
  mesh: default
  metadata:
    namespace: default
    name: template-1
  selectors:
    ...
  conf:
    imports:
      ...
    resources:
      ...
  ```

  actually implemented:

  ```yaml
  apiVersion: kuma.io/v1alpha1
  kind: ProxyTemplate
  mesh: default
  metadata:
    namespace: default
    name: template-1
  spec:
    selectors:
      ...
    imports:
      ...
    resources:
      ...
  ```

### Related issues:

* #406
