### ISSUE TITLE
When a user defines Pod-level security context, `kuma-init` container fails with `Permission denied (you must be root)`

### ISSUE THREAD

**Issue by yskopets** [Kong/kuma#571]
### Summary

* When a user defines `Pod`-level security context, `kuma-init` container fails with `Permission denied (you must be root)`

### Steps To Reproduce

1. Defines `Pod`-level security context with `runAsUser: 1000`

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example-app
  name: example-app
  namespace: kuma-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: example-app
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```

2. `kuma-init` container will fail with

```
iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
+ dump
+ iptables-save
iptables-save v1.6.0: Cannot initialize: Permission denied (you must be root)
```

**Comment by codeofnode** [comment]
why don't we run kuma sidecar with NET_ADMIN capability
```
                SecurityContext: &kube_core.SecurityContext{
                        RunAsUser:  &i.cfg.SidecarContainer.UID,
                        RunAsGroup: &i.cfg.SidecarContainer.GID,
                       Capabilities: &kube_core.Capabilities{
                               Add: []kube_core.Capability{
                                       kube_core.Capability("NET_ADMIN"),
                               },
                       },
                },
```

**Comment by yskopets** [comment]
@codeofnode Hey!

Sorry for delay.

I happens that `kuma-init` container already has a `NET_ADMIN` capability (see [here](https://github.com/Kong/kuma/blob/master/app/kuma-injector/pkg/injector/injector.go#L251)).

So, the problem is that we don't assign explicit `RunAsUser` and `RunAsGroup`, that should be `0` in this case.

This is a perfect "first issue" 😉

**Comment by codeofnode** [comment]
Using a new proxy-init image, with below Dockerfile
```
FROM istio/proxy_init:1.3.8
RUN chmod u+s /sbin/xtables-multi
```
will make things work

**Comment by yskopets** [comment]
@codeofnode Hey!

Thanks a lot for looking into this!

I've double-checked that this approach does work in practice.

I'm now considering the security aspect of doing it.

There are other ways to let an arbitrary user to run a program as a `root`. E.g. [sudoers](https://unix.stackexchange.com/questions/18830/how-to-run-a-specific-program-as-root-without-a-password-prompt).

Sorry, need some time to make my mind.

**Comment by codeofnode** [comment]
You are right, there might be some security concern. How about below solution?
image = `codeofnode/istio-proxy-init:1.3.8-1`
```
FROM istio/proxy_init:1.3.8
RUN setcap cap_net_raw,cap_net_admin+eip /sbin/xtables-multi
```

But following (adding extra NET_RAW) might be required for kuma init container.

```
                SecurityContext: &kube_core.SecurityContext{
                        Capabilities: &kube_core.Capabilities{
                               Add: []kube_core.Capability{
                                         kube_core.Capability("NET_ADMIN"),
+                                       kube_core.Capability("NET_RAW"),
                               },
                       },
                },
```

**Comment by tuananh2508** [comment]
I have problem when try to use Kuma with Loki 
Here is what showing when using `kubectl describe pod` 
I have try using above Docker Image, but still not fixed it.

Events:
  Type     Reason                Age                   From                             Message
  ----     ------                ----                  ----                             -------
  Normal   Scheduled             2m53s                 default-scheduler                Successfully assigned default/loki-0 to pool-7otl9mgp-2x9bltidkfd4kfco-node-khhbgqq3
  Normal   CreatedKumaDataplane  2m42s                 k8s.kuma.io/dataplane-generator  Created Kuma Dataplane: loki-0
  Normal   UpdatedKumaDataplane  66s (x2 over 2m41s)   k8s.kuma.io/dataplane-generator  Updated Kuma Dataplane: loki-0
  Warning  Failed                43s (x12 over 2m42s)  kubelet                          Error: container's runAsUser breaks non-root policy
  Normal   Pulled                28s (x13 over 2m42s)  kubelet                          Container image "docker.io/kumahq/kuma-init:1.2.3" already present on machine

**Comment by simonwh** [comment]
Having same issue as @tuananh2508, but with cert-manager (latest helm chart). Cert-managers `runAsNonRoot: true` seems to be conflicting with the sidecars securityContext?

**Comment by lobkovilya** [comment]
@simonwh @tuananh2508 could you please share full config of the deployment? By default Kuma injects a sidecar that has the following securityContext:
```yaml
securityContext:
  runAsGroup: 5678
  runAsUser: 5678
```
These UID and GID could be changed using `KUMA_RUNTIME_KUBERNETES_INJECTOR_SIDECAR_CONTAINER_UID` env variable. By default, these values should not break `runAsNonRoot: true` policy

**Comment by zd9KgA** [comment]
@lobkovilya The problem seems to be `kuma-init`, which is not allowed to change to UID/GID 0 if `runAsNonRoot` is set to `true` in the pod's `securityContext` settings.

**Comment by konczbenedek** [comment]
We have the same problem as @simonwh @tuananh2508. As @zd9KgA pointed out, this problem is related to the kuma-init init-container and not the kuma-sidecar so cannot be fixed with `KUMA_RUNTIME_KUBERNETES_INJECTOR_SIDECAR_CONTAINER_UID`.  Does anybody have a solution for scenarios where you cannot change the `runAsNonRoot` value in the pod's  `securityContext`? Some examples are cert-manager http solvers, as mentioned before, PGO postgres operators. There are many scenarios when you can not control pod level settings.

**Comment by voidlily** [comment]
I was able to get this to work with an init patch based on the one originally mentioned in the proposal

```
# https://docs.konghq.com/mesh/latest/introduction/kuma-requirements/
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: nonroot-fix
  namespace: kuma-system
spec:
  initPatch:
    - op: add
      path: /securityContext/runAsNonRoot
      value: "false"
    - op: remove
      path: /securityContext/runAsUser
```

I was not able to get runAsNonRoot: true to work because install_transparent_proxy specifically checks for uid 0 https://github.com/kumahq/kuma/blob/b8de3099df7e6d80ea3ad261adec46b45429decf/app/kumactl/cmd/install/install_transparent_proxy.go#L145-L146

This may be okay in my case because at the podSecurityContext, I set runAsNonRoot to true, and only change it to false in the initContainer
