### ISSUE TITLE
Kumactl crashes when applying DP ressource

### ISSUE THREAD

**Issue by Docteur-RS** [Kong/kuma#602]
### Summary

I am trying to connect a Debian to a Kubernetes mesh. From the Debian I connected to the kubernetes CP successfully.   

Now I want to add a DP for a service running on the Debian.  
**Unfortunately when I apply the DP it crashes with the following error:**

```
Error: Could not retrieve a resource (Internal Server Error)
```

The DP I'm trying to apply:
```
type: Dataplane
mesh: default
name: backend-1
networking:
  inbound:
  - interface: 127.0.0.1:8000:8080
    tags:
      service: backend
  outbound:
  - interface: :3000
    service: myservice.kuma-demo.svc
```
Trying different ways to apply the DP always results in the same errors.

```
$ ./kumatcl apply -f <DP_FILE>
=> crash
$ cat <DP_FILE> | ./kumatcl apply -f -
=> crash
```

### Steps To Reproduce

1. Connect to remote CP
2. Apply DP using kumatcl
3. Crash...

### Additional Details & Logs

- Version
```
./kumactl version
0.3.2
```
- Error logs  
`Error: Could not retrieve a resource (Internal Server Error)`  
- Configuration
```
./kumactl get dataplanes
MESH      NAME                                              TAGS
default   myservice-545df86d5b-67kwc.kuma-demo            app=deploy2 pod-template-hash=545df86d5b role=backend service=myservice.kuma-demo.svc:3000
default   es-rjqvh.kuma-demo                                component=elasticsearch service=elasticsearch.kuma-demo.svc:80
default   kuma-demo-app-7f799bbfdf-s8kvf.kuma-demo          app=kuma-demo-frontend env=prod pod-template-hash=7f799bbfdf service=frontend.kuma-demo.svc:80 version=v8
default   kuma-demo-backend-v0-6548b88bf8-h2gq2.kuma-demo   app=kuma-demo-backend env=prod pod-template-hash=6548b88bf8 service=backend.kuma-demo.svc:3001 version=v0
default   redis-master-6d4cf995c5-czlxl.kuma-demo           app=redis pod-template-hash=6d4cf995c5 role=master service=redis.kuma-demo.svc:6379 tier=backend
```
- Platform and Operating System
VM : Debian
Kubernetes cluster : CentOS7

**Comment by yskopets** [comment]
@Docteur-RS Hey!

If you deploy `Kuma` on `k8s`, you can only use `kumactl` for read-only operations.

On `k8s`, you will need to use `Dataplane` CRD and **kubectl**.

E.g., your example translated into `Dataplane` CRD will look the following way:

```shell
echo "
apiVersion: kuma.io/v1alpha1
kind: Dataplane
mesh: default
metadata:
  name: dataplane-outside-k8s
  namespace: default
spec:
  networking:
    inbound:
    - interface: 127.0.0.1:8000:8080 # Please use IP address of the Debian VM
      tags:
        service: backend # for Dataplanes outside `k8s` you can pick any `service` value
    outbound:
    - interface: :3000
      service: myservice.kuma-demo.svc:3000
" | kubectl apply -f -
```

Notice that:
* if you want your `Dataplane` to be accessible by other `Dataplanes`, you need to use a non-loopback interface in `inbound` listener (right now it's `127.0.0.1:`)
* the value of `service` inside `outbound` listener should be `myservice.kuma-demo.svc:3000` (notice `:3000` suffix)
  * for `Dataplanes` running outside `k8s` you can pick any `service` value, like you did with `service: backend`
  * for `Dataplanes` running on `k8s` Kuma chooses `service` value automatically
    * you can see that value in the output of 
      ```
      kumactl get dataplanes
      ```

Hope that helps!

**Comment by Docteur-RS** [comment]
Thank you for your answer! It helps a lot.  

I still have a few interrogations though...  

My use case is still the same. I would like the application running on Debian to be able to send requests to a pod on Kubernetes while both being part of the Kuma mesh service.

### Question 1
 In the **outboud** section should I use the "name" of the target dataplane I want to connect to ? 
 => result of `kumactl get dataplanes`  
           **or**   
Should I use the kubernetes way ?  
=> `svc.namespace.cluster.local`   

### Question 2
 What IP should I curl from the Debian to access the service ?  

In the documentation for the Debian install they curl 127.0.0.1 which in the end gets redirected. But in my case I don't see what component would do this ?  
I don't even see an Envoy process running on the Debian VM.  

And I don't see why I should run any other components like a controlplane on the Debian as I am already connected to the one on Kubernetes...  

Thanks for your time!

**Comment by yskopets** [comment]
@Docteur-RS Hey!

Yeah, this use case should already be possible. Maybe with some constraints.

Regarding **Question 1**:

`outbound` listener is essentially a local representation of a remote service. 

So, `service` field  of the `outbound` listener should have the same value as `service` tag on the `inbound` listeners of those Dataplanes that you want to connect to.

E.g., let's consider an example with 2 apps: `web` and `backend`, where `web` makes requests to the `backend`.

On `Universal`, you would need to manually define the following `Dataplanes` for that case:

```yaml
type: Dataplane
mesh: default
name: backend-01
networking:
  inbound:
  - interface: 192.168.0.1:17070:7070
    tags:
      service: backend # notice value of `service` tag
```

```yaml
type: Dataplane
mesh: default
name: web-01
networking:
  inbound:
  - interface: 192.168.0.1:18080:8080
    tags:
      service: web
  outbound:
  - interface: :3001
    service: backend # notice value of `service` field
``` 

Notice that `service` field of the `outbound` listener in Dataplane `web-01` has the same value "`backend`" as the `service` tag of the `inbound` listener in Dataplane `backend-01`.

This configuration means that whenever your `web` app needs to make a request to `backend` app, it should make a call to `127.0.0.1:3001` (instead of using DNS resolution, etc).

`Kuma` will configure the dataplane (Envoy) that runs next to the `web` app to listen on `127.0.0.1:3001` and route received traffic to those `Dataplanes` that have an `inbound` listener with tag `service: backend`, e.g. `backend-01` in this example.

On `Kubernetes`, `Kuma` automatically creates `Dataplane` definitions out of native `Kubernetes` objects, such as `Pod` and `Service`.

So, continuing the example, on `Kubernetes` you will automatically get the following definition of `backend-01` (as long as you have `Deployment` and `Service`):

```yaml
apiVersion: kuma.io/v1alpha1
kind: Dataplane
mesh: default
metadata:
  name: backend-5c89f4d995-p4gpr
  namespace: kuma-example
spec:
  networking:
    inbound:
    - interface: 10.244.0.16:7070:7070
      tags:
        app: backend
        pod-template-hash: 5c89f4d995
        service: backend.kuma-example.svc:7070 # notice the value of `service` tag
    transparentProxying:
      redirectPort: 15001
```

Notice the auto-generated value of `service` tag.

Assuming that your `web-01` is running outside of `k8s`, you need to put `backend.kuma-example.svc:7070` as a value of `service` field on `outbound` listener.

Regarding **Question 2**:

To test whether a dataplane (Envoy) has been configured correctly, you could make a request to the `outbound` listener, e.g.

```
curl 127.0.0.1:3001 # port `3001` comes from the definition of Dataplane `web-01`
```

Internally, your local dataplane (running next to `web` app) will forward requests to the remote dataplane (running on `k8s` next to `backend` app). It will use the IP address of a `k8s` `Pod` for that.

So, you could also check whether that IP is accessible from your VM., e.g.

```
curl 10.244.0.16:7070 # IP address and port come from the definition of Dataplane `backend-5c89f4d995-p4gpr`
```

Regarding **Question 3**:

Yes, you don't need to run another Control Plane.

Hope that helps!
