### ISSUE TITLE
Mesh does not update when configuring tracing backend on kubernetes

### ISSUE THREAD

**Issue by devadvocado** [Kong/kuma#638]
### Summary

When configuring tracing backend on kubernetes, mesh resource does not update correctly to show tracing changes.

### Steps To Reproduce

1. Apply tracing backend
```
cat <<EOF | kubectl apply -f - 
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  mtls:
    ca:
      builtin: {}
    enabled: true
  metrics:
    prometheus: {}
  tracing:
    defaultBackend: jaeger
    backends:
    - name: jaeger
      sampling: 100.0 
      zipkin:
        url: http://simplest-collector.default:9411/api/v1/spans
EOF
```
2. Curl mesh endpoint to check
```
curl localhost:5681/meshes
{
 "items": [
  {
   "type": "Mesh",
   "name": "default",
   "mtls": {
    "ca": {
     "builtin": {}
    },
    "enabled": true
   },
   "tracing": {},
   "metrics": {
    "prometheus": {
     "port": 5670,
     "path": "/metrics"
    }
   }
  }
 ]
}
```

### Additional Details & Logs

- Version: 0.4.0
- Platform and Operating System: Kubernetes
