### ISSUE TITLE
Store creation date of every entity

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kuma#661]
Store the UTC creation date timestamp for every entity that is being created.

**Comment by tharun208** [comment]
Created a PR for this @subnetmarco 😀

**Comment by jakubdyszkiewicz** [comment]
We store this already, but it isn't exposed in the API (we use it to sort conflicts on matching policies)
We store creation time and modification time, but keep in mind that creation time is equal to modification time on K8S.

Do you have any format in mind on how to expose it? @subnetmarco 
One of the way could be this
```
type: Dataplane
mesh: default
name: redis-1
creationTime: 2020-04-05T21:18:35Z
modificationTime: 2020-04-05T21:18:35Z
networking:
  address: 192.168.0.1
  inbound:
  - port: 9000
    servicePort: 6379
    tags:
      service: redis
```
