### ISSUE TITLE
Generate XDS for Ingress Dataplane

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kuma#776]
### Summary

Generate XDS for Ingress Dataplane.

Implementation tips:

I think the most suitable way to implement this is to provide implementation to this
```
type ResourceGenerator interface {
	Generate(xds_context.Context, *model.Proxy) ([]*model.Resource, error)
}
```
This will be a merge of `InboundProxyGenerator` and `OutboundProxyGenerator`.
Given such Ingress dataplane
```
type: Dataplane
mesh: default
name: ingress-1
networking:
  ingress: true # to decide: we need a marker that this is an ingress
  address: 1.1.1.4
  inbound:
  - port: 10000 # picked automatically
    tags:
      service: backend
      cluster: cluster-1
  - port: 10001 # picked automatically
    tags:
      service: backend
      version: v2
      cluster: cluster-1
```
We will open 2 inbound listeners, create 2 Envoy clusters. Each Envoy cluster will have corresponding EDS with endpoints for all DPs (inbounds) in a Kuma cluster.
