### ISSUE TITLE
Kuma DP deployment for Ingress Dataplane

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kuma#777]
### Universal
Provide instructions on how to start Ingress Dataplane. The flow is similar.
1) Apply a DP
```
type: Dataplane
mesh: default
name: ingress-1
networking:
  ingress: true # to decide: we need a marker that this is an ingress
  address: 1.1.1.4
```
2) Generate token
3) Start Kuma DP

Reconciliation loop will fill inbounds for this gateway.

### Kubernetes
Provide `kumactl install ingress-dataplane` that will create a deployment of Ingress that can be scaled if needed.

My idea for implementation:
* Command above will create Deployment with new annotation to the Pod.
* Pod converter will generate Ingress Dataplane definitions but not inbounds
* Reconciliation loop (same as on Universal) will fill inbounds for this gateway
