### ISSUE TITLE
Introduce Ingress Dataplane model

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kuma#778]
### Summary

Extend Dataplane model to introduce Ingress Dataplane.

My idea for the model
```
type: Dataplane
mesh: default
name: ingress-1
networking:
  ingress: {}
  address: 1.1.1.4
```
For now `ingress: {}` has empty options, but leave an option for extension.
Ingress Dataplane can have 0 inbounds (it can be started before there are any services in the cluster)
Ingress Dataplane cannot have any outbounds.
Ingress Dataplane cannot be combined with Gateway.
